sudo: required
dist: trusty
language: java
jdk:
  - openjdk11

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd employeeservice
  - sh -c './gradlew test'
  - docker build -t $DOCKER_USERNAME/employeeservice:latest .
  - docker push $DOCKER_USERNAME/employeeservice
  - cd ../errorservice
  - sh -c './gradlew test'
  - docker build -t $DOCKER_USERNAME/errorservice:latest .
  - docker push $DOCKER_USERNAME/errorservice
