version: "2"

services:
  employeeservice:
    image: hvvka/employeeservice
    ports:
      - "9000-9001:9000"
  errorservice:
    image: hvvka/errorservice
    container_name: errorservice
    ports:
      - "8080:8080"
  mysql:
    extends:
      file: mysql.yml
      service: mysql
