version: "3"

services:
    employeeservice:
        image: hvvka/employeeservice
        container_name: employeeservice
        ports:
            - "9000:9000"
     errorservice:
        image: hvvka/errorservice
        container_name: errorservice
        ports:
            - "8080:8080"
