spring:
  jpa:
    show-sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:../xd
    driverClassName: org.h2.Driver
    username: xd
    password:
server:
  port: 9000

errorservice:
  url: http://localhost:8080/api/exception
